export const GET_ERRORS = "GET_ERRORS";
export const GET_CURRENT_EXCHANGE_RATE = "GET_CURRENT_EXCHANGE_RATE";
export const GET_EXCHANGE_RATE_BY_DATE = "GET_EXCHANGE_RATE_BY_DATE";
export const GET_EXCHANGE_RATE_BY_MONTH = "GET_EXCHANGE_RATE_BY_MONTH";
